### ISSUE TITLE
Fix build with datapackage >= 0.7.0

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/ex-continuous-data-integration#3]
I've just released datapackage 0.7.0, which changes the names "metadata" to "descriptor", keeping it more consistent with the spec. This will break this code.

To avoid this from happening in the future, it would be useful to pin datapackage's version on https://github.com/frictionlessdata/ex-continuous-data-integration/blob/master/scripts/requirements.txt

**Comment by danfowler** [comment]
👍
